<<<<<<< HEAD

=======
>>>>>>> parent of bde2d44... bug
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD

namespace News.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tintuc
{

    public int id { get; set; }

    public string name { get; set; }

    public string img { get; set; }

    public string description { get; set; }

    public string link { get; set; }

    public string detail { get; set; }

    public string meta { get; set; }

    public Nullable<bool> hide { get; set; }

    public Nullable<int> position { get; set; }

    public Nullable<System.DateTime> datebegin { get; set; }

    public int id_m { get; set; }



    public virtual menu menu { get; set; }

}

=======
namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public string detail { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public int id_m { get; set; }
    
        public virtual menu menu { get; set; }
    }
>>>>>>> parent of bde2d44... bug
}
