<<<<<<< HEAD

=======
>>>>>>> parent of bde2d44... bug
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD

namespace News.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int ID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

}

=======
namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
    }
>>>>>>> parent of bde2d44... bug
}
